### ISSUE TITLE
Rename snap

### ISSUE THREAD

**Issue by soumyaDghosh** [CapeCrusader321/Celluloid-Snap#1]
Is the `celluloid` name not available in snap-store? If not, lemme talk then. If available, create a store-request to rename the snap in forum.

**Comment by soumyaDghosh** [comment]
Tested the snap... no crash there when maximizing.

**Comment by CapeCrusader321** [comment]
> Is the `celluloid` name not available in snap-store? If not, lemme talk then. If available, create a store-request to rename the snap in forum.

Under which category is renaming done in snapcraft ?/

**Comment by soumyaDghosh** [comment]
store-requests. Also, I saw Alex has already said that... Well ask him to rename it. That'll be all. But, don't publish the snap now. The snap is more than 100mb, you think that's normal for a video player!

**Comment by soumyaDghosh** [comment]
https://snapcraft.io/register-name-dispute?snap-name=celluloid&store=


You can use that too

**Comment by soumyaDghosh** [comment]
Kindly use better, readable and understandable commit messages, don't just keep it `update ....`. Please. Please. Anyways, sending you a PR soon.

**Comment by CapeCrusader321** [comment]
> 

I am doing it, check out recent one's you will get better commit mesages

**Comment by soumyaDghosh** [comment]
A better and lightweight snap.

**Comment by soumyaDghosh** [comment]
````
name: celluloid-snap
base: core22
version: '0.25'
adopt-info: celluloid-snap
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

slots:
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid


apps:
  celluloid-snap:
    command: usr/bin/celluloid
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    desktop: $SNAP/usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - network
      - network-status
      - screen-inhibit-control
    slots:
      - mpris
parts:
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - --prefix=/snap/celluloid-snap/current/usr
    build-packages:
      - libmpv-dev
      - liblua5.3-dev
      - libepoxy-dev
      - python3-dev
    override-pull: |
      craftctl default
      sed -e 's|Icon=io.github.celluloid_player.Celluloid|Icon=$SNAP/usr/share/icons/hicolor/scalable/apps/io.github.celluloid_player.Celluloid.svg|' -i data/io.github.celluloid_player.Celluloid.desktop.in
    stage-packages:
      - youtube-dl
      - libmpv1
    organize:
      snap/celluloid-snap/current/usr: usr
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include
````

**Comment by CapeCrusader321** [comment]
I will also need some help with building latest libmpv can you please help ??

**Comment by soumyaDghosh** [comment]
> I Have a doubt ?? The desktop file supplied with the app has exec set to celluloid %U but my snap is celluloid-snap will the desktop file still open the snap properly. In another case lets take freetube snap there i force the snap to run without sandboxing but the pre shipped desktop file doesnt assume this will it still work properly ?

Snap always auto-creates a desktop file under `meta/gui`, there it takes the desktop file you gave in the `desktop` section as reference. Now in this, ig there is some error, you keep the desktop files, this is due to the snap name problem. You'll need to chenge the `Exec=...` line. Well, in other cases they'll work, because snap creates a executable file under `/snap/bin` which executes the command that you'll give in the `apps.command` part. Now, if you say. the desktop file says to run freetube, then, it'll run the `freetube` executable from `/snap/bin` which will again run the command that you've set.

**Comment by CapeCrusader321** [comment]
> > I will also need some help with building latest libmpv can you please help ??
> 
> Sending you soon,
> 
> EDIT: Sorry, it'll be a little late. Have some assignments left over.

No problem

**Comment by soumyaDghosh** [comment]
Enable discussion in your repos. Discussing like this in an issue, doesn't look good. Also, any means to connect with you personally?

**Comment by CapeCrusader321** [comment]
Maybe gmail too ?

**Comment by soumyaDghosh** [comment]
````
name: celluloid-snap
base: core22
version: '0.25'
adopt-info: celluloid-snap
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

slots:
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid


apps:
  celluloid-snap:
    command: usr/bin/celluloid
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - network
      - network-status
      - screen-inhibit-control
    slots:
      - mpris
parts:
  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.1
    after: [ffmpeg, celluloid-snap]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dlibmpv=true
      - -Dcplayer=false
      - -Dbuild-date=false
      - -Dalsa=disabled
    build-packages:
      - ladspa-sdk
      - libffmpeg-nvenc-dev
      - vulkan-tools
    stage-packages:
      - libass9
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - --prefix=/snap/celluloid-snap/current/usr
    build-packages:
      - libmpv-dev
      - liblua5.3-dev
      - libepoxy-dev
      - python3-dev
    stage-packages:
      - luajit
      - v4l-utils
      - libffmpeg-nvenc-dev
      - libass9
      - uchardet
      - youtube-dl
    override-pull: |
      craftctl default
      sed -e 's|Icon=io.github.celluloid_player.Celluloid|Icon=$SNAP/usr/share/icons/hicolor/scalable/apps/io.github.celluloid_player.Celluloid.svg|' -i data/io.github.celluloid_player.Celluloid.desktop.in
    organize:
      snap/celluloid-snap/current/usr: usr
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - celluloid-snap
      - ffmpeg
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gtk-common-themes
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
````

Completely initial but try this
