### ISSUE TITLE
Crashes when maximized

### ISSUE THREAD

**Issue by CapeCrusader321** [CapeCrusader321/Celluloid-Snap#10]
Celluloid crashes atleast in my setup under both xorg and picom when i try doing maximize and then minimize using the button provided in the player.

**Comment by soumyaDghosh** [comment]
I tested in wayland, there was no such crash. The celluloid snap seemed fine in my setup. Can you give some logs?

**Comment by CapeCrusader321** [comment]
> I tested in wayland, there was no such crash. The celluloid snap seemed fine in my setup. Can you give some logs?

(io.github.celluloid_player.Celluloid:8216): Gtk-WARNING **: 18:58:42.283: Couldn't unexport handle for GdkX11Toplevel surface, unsupported windowing system
Segmentation fault (core dumped)

**Comment by CapeCrusader321** [comment]
This is somewhat similar to -->  https://github.com/celluloid-player/celluloid/issues/480

**Comment by CapeCrusader321** [comment]
@soumyaDghosh  here is the strace output, that i think is useful ??

![sc04](https://user-images.githubusercontent.com/100503303/230722601-f8a92589-67fb-4e8d-8193-c99fba134c7d.png)

**Comment by CapeCrusader321** [comment]
https://github.com/celluloid-player/celluloid/issues/855

**Comment by soumyaDghosh** [comment]
Can you tell me your setup/scenario.
like:
1. OS
2. Desktop Environment
3. Display Server(X11/Wayland)
4. Graphics Card(Looking for NVIDIA mainly)
5. snap file (Using the latest edge from snap-store)

**Comment by soumyaDghosh** [comment]
https://snapcraft.io/ffmpeg

This ffmpeg can be used. Instead of building it from source.

**Comment by soumyaDghosh** [comment]
BTW, I got the `plots` snap today. I requested for that name yesterday and got it just after some time

**Comment by soumyaDghosh** [comment]
Reproduced it.... But not exactly same as yours

**Comment by CapeCrusader321** [comment]
> https://snapcraft.io/ffmpeg
> 
> This ffmpeg can be used. Instead of building it from source.

That will bloat the snap plus its outdated and unmaintained

**Comment by CapeCrusader321** [comment]
> Reproduced it.... But not exactly same as yours [Screencast from 2023-04-18 19-28-08.webm](https://user-images.githubusercontent.com/72045785/232801002-a736b04a-bffb-4dec-a346-feb88f974771.webm)

Try using the media players inbuilt or internal  fullscreen or maximum window button

**Comment by CapeCrusader321** [comment]
> Can you tell me your setup/scenario. like:
> 
>     1. OS
> 
>     2. Desktop Environment
> 
>     3. Display Server(X11/Wayland)
> 
>     4. Graphics Card(Looking for NVIDIA mainly)
> 
>     5. snap file (Using the latest edge from snap-store)

1) Lubuntu 22.04.2
2) Lxqt obviously X11 
3) Normal Intel i3 2017 4gb ram  laptop with no graphics card etc.
4) Using Celluloid snap from stable channel

**Comment by soumyaDghosh** [comment]
Let me give a shot in github CI then :-)

**Comment by soumyaDghosh** [comment]
Let me give a shot in github CI then :-)

**Comment by CapeCrusader321** [comment]
> Let me give a shot in github CI then :-)

Hey there i dont think staging the snap is good as it just bloats the app and make it heavy plus the ffmpeg snap is outdated and poorly maintained, i am moving on with building from source, thanks for the suggestion thpugh.

**Comment by soumyaDghosh** [comment]
Yes, I changed it, check the PR. Kindly think on my suggestion about commit message though. That's useful in all of your repos.

**Comment by CapeCrusader321** [comment]
> 

I have already implemented (commit mssgs) it for celluloid will do in others if possible.

**Comment by CapeCrusader321** [comment]
@soumyaDghosh this is the output with my existing YAML ;

Failed to stage: parts list the same file with different contents or permissions.
Parts 'celluloid-snap' and 'ffmpeg' list the following files, but with different contents or permissions:
    usr/bin/ffmpeg
    usr/bin/ffprobe

**Comment by soumyaDghosh** [comment]
Wait, don't make any changes to the current repo any more. I am sending a final one with ffmpeg. You just kindly build it. Cos, I am at my home and due to online classes most of my internet is used.

**Comment by soumyaDghosh** [comment]
```
name: celluloid-snap
base: core22
version: '0.25'
icon: snap/gui/gnome-mpv.svg
adopt-info: celluloid-snap
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
slots:
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid


apps:
  celluloid-snap:
    command: usr/bin/celluloid
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    extensions: [gnome]
    common-id: io.github.celluloid_player.Celluloid 
    plugs:
      - home
      - audio-playback
    slots:
      - mpris
    
parts:  
  mpv:
    source: https://github.com/mpv-player/mpv.git
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dlibmpv=true
    build-packages:
      - curl
      - libavcodec-dev
      - libavfilter-dev
      - libass-dev
      - libx264-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
    prime:
      - usr/lib/*/libmpv*
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include  
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    after: [mpv, ffmpeg]
    plugin: meson
    meson-parameters:
      - --prefix=/snap/celluloid-snap/current/usr
    build-packages:
      - libepoxy-dev
      - luajit
    stage-packages:  
      - libv4l-0
      - libv4l2rds0
      - libv4lconvert0
      - liblapack3
      - libblas3
    organize:
      /snap/celluloid-snap/current/usr: usr
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
  cleanup:
    after: [celluloid-snap, mpv, ffmpeg, nv-codec-headers]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done    
```

Try this. Just try this, don't push it.
